import subprocess
import re


def scan_wifi():
    """
    Scan nearby Wi-Fi networks using Windows netsh.
    """

    command = [
        "netsh",
        "wlan",
        "show",
        "networks",
        "mode=bssid"
    ]

    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="ignore",
            timeout=15
        )

    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "error": "Wi-Fi scan timed out",
            "networks": []
        }

    if result.returncode != 0:
        return {
            "success": False,
            "error": result.stderr.strip() or "Wi-Fi scan failed",
            "networks": []
        }

    networks = parse_wifi_output(result.stdout)

    return {
        "success": True,
        "count": len(networks),
        "networks": networks
    }


def parse_wifi_output(output):
    """
    Parse output generated by:

    netsh wlan show networks mode=bssid
    """

    networks = []

    current_ssid = None
    current_authentication = None
    current_encryption = None
    current_bssid = None
    current_signal = None
    current_channel = None
    current_radio = None

    for raw_line in output.splitlines():

        line = raw_line.strip()

        # New SSID
        if re.match(r"^SSID\s+\d+\s*:", line, re.IGNORECASE):

            # Save previous BSSID/network
            if current_ssid and current_bssid:
                networks.append({
                    "ssid": current_ssid,
                    "bssid": current_bssid,
                    "authentication": current_authentication,
                    "encryption": current_encryption,
                    "signal": current_signal,
                    "channel": current_channel,
                    "radio": current_radio
                })

            current_ssid = line.split(":", 1)[1].strip()

            current_authentication = None
            current_encryption = None
            current_bssid = None
            current_signal = None
            current_channel = None
            current_radio = None

        # Authentication
        elif line.lower().startswith("authentication"):
            current_authentication = line.split(":", 1)[1].strip()

        # Encryption
        elif line.lower().startswith("encryption"):
            current_encryption = line.split(":", 1)[1].strip()

        # BSSID
        elif re.match(r"^BSSID\s+\d+\s*:", line, re.IGNORECASE):
            current_bssid = line.split(":", 1)[1].strip()

        # Signal
        elif line.lower().startswith("signal"):
            value = line.split(":", 1)[1].strip()

            match = re.search(r"(\d+)", value)

            if match:
                current_signal = int(match.group(1))

        # Channel
        elif line.lower().startswith("channel"):
            value = line.split(":", 1)[1].strip()

            match = re.search(r"(\d+)", value)

            if match:
                current_channel = int(match.group(1))

        # Radio type
        elif line.lower().startswith("radio type"):
            current_radio = line.split(":", 1)[1].strip()

    # Save final network
    if current_ssid and current_bssid:
        networks.append({
            "ssid": current_ssid,
            "bssid": current_bssid,
            "authentication": current_authentication,
            "encryption": current_encryption,
            "signal": current_signal,
            "channel": current_channel,
            "radio": current_radio
        })

    return networks